### PR TITLE
Added item_ prefix

### PR DESCRIPTION
**Pull request by CmdrJorgs**
Added item_ prefix to "sku" and "gtin" to reflect modern Biff standards.

### CODE REVIEW

**Comment by CmdrJorgs** [comment]
@tyssejc Mind reviewing? Thanks!

**Comment by StevenJRowe123** [comment]
@CmdrJorgs , @tyssejc Can we talk about this before merging into the master branch?

**Comment by tyssejc** [comment]
@CmdrJorgs thanks for the PR!

Quick background: the GA4 dataLayer spec is based on Google's official events and event parameters. If you haven't already, see `item` params for GA4 events in the [GA4 Events documentation](https://developers.google.com/analytics/devguides/collection/ga4/reference/events#view_item_item). Some parameters have the `item_` prefix (`item_id`, `item_name`, `item_brand`, etc.), while others do not (`affiliation`, `coupon`, `price`, `quantity`, etc.). All of the params with the `item_` prefix are [GA4 counterparts to UA ecommerce params](https://support.google.com/analytics/answer/10119380?hl=en&ref_topic=11192706), although not all UA counterparts have the `item_` prefix (`price`, `quantity`, etc.).

I don't think it's necessary (or even desirable) to add `item_` to all GA4 params — in the case of `gtin` or `sku`, I don't see a compelling reason to make this change.

@StevenJRowe123 anything you want to add?

**Comment by tyssejc** [comment]
Closing this PR — let's continue to have a conversation about the best way to introduce changes to the spec going forward.

**Pull request closed without merging**
